---
spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
#      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
      url: jdbc:h2:mem:~/awsm
      username: sa
      password:

registration:
  rateLimit: 1